pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
        sh 'java -jar target/your-java-application.jar'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npm install'
        // Additional npm commands as needed
        // e.g., npm run build, npm test, etc.
        sh 'node hello.js'
      }
    }
  }
}
